test001.c:8: エラー: `a' が再宣言されています.
test001.c:8: エラー: ここで宣言されていました.
test001.c: 函数 `g' :
test001.c:16: エラー: `b' が再宣言されています.
test001.c:15: エラー: ここで宣言されていました.
test001.c:20: エラー: `c' が再宣言されています.
test001.c:19: エラー: ここで宣言されていました.
test001.c: 函数 `h' :
test001.c:26: エラー: 仮引数 `d' が再宣言されています.
test001.c:24: エラー: ここで宣言されていました.
