test000.c: 函数 `f' :
test000.c:6: エラー: continue 文がループの中でないところに出現しました.
test000.c:9: エラー: continue 文がループの中でないところに出現しました.
test000.c:13: エラー: continue 文がループの中でないところに出現しました.
test000.c:17: エラー: continue 文がループの中でないところに出現しました.
