test002.c: 函数 `f' :
test002.c:6: エラー: goto 文で.
test002.c:10: エラー: ここにジャンプしますが,
test002.c:8: エラー: `a' がここで宣言されています.
test002.c:16: エラー: goto 文で.
test002.c:13: エラー: ここにジャンプしますが,
test002.c:8: エラー: `a' がここで宣言されています.
